### ISSUE TITLE
Cannot read property "players" of null

### ISSUE THREAD

**Issue by SpaceCowboy3514** [vinceau/project-clippi#102]
I keep on getting this error
![image](https://user-images.githubusercontent.com/57578722/89420071-36f1a780-d700-11ea-8618-f38b0ffb75d4.png)

**Comment by SpaceCowboy3514** [comment]
this did not happen on prior versions

**Comment by vinceau** [comment]
Fixed in 0650e59. This happens when processing corrupted SLP files.
