### ISSUE TITLE
List of tags for "Write to file" option

### ISSUE THREAD

**Issue by priverop** [vinceau/project-clippi#117]
I'm trying to understand how the different actions work, and I'm very confused with the "write to file" action.

I've seen in one of your medium articles that are some tags such as {{date}}, {{time}} or {{clipID}}. 

Can we get an extensive list of these with a little explanation? Or I can extract them from the code if you can tell me where to find them.

Thanks!

**Comment by vinceau** [comment]
The tags is actually deprecated somewhat. I think date and time might still work, I'm not sure. But chaining actions together and exposing tags to the subsequent action was extremely convoluted. So to answer your question, there's no real list of tags as I'm not even sure myself that they work anymore. Might try bring it back if there is demand but for the time being there's only like 3 people who actually use Clippi Automator anyways. 😂

**Comment by priverop** [comment]
Totally fine! :)

Good job with the tool.
