### ISSUE TITLE
I cant seem to set where clippi looks for dolphin

### ISSUE THREAD

**Issue by shayyya1** [vinceau/project-clippi#120]
I do not have dolphin in the default location, how do i set clippi to use dolphin in a non-default location? I cant find a setting, tho it would not surprise me if one existed

**Comment by vinceau** [comment]
Go to Settings > Info, then click the Clippi logo 7 times until it faces the other direction. Then go to Playback section under Settings and you should have the option to set the Playback Dolphin Path.
