### ISSUE TITLE
Error when trying to scrape through replays

### ISSUE THREAD

**Issue by colelio1** [vinceau/project-clippi#121]
![clippi error](https://user-images.githubusercontent.com/80544995/110988607-c4ecdb00-833e-11eb-917a-4e37c4195c5f.png)

Getting this odd error when trying to scrape through replays or when trying to play a .json file. Only became an issue since 1.67 update of slippi desktop app.

**Comment by vinceau** [comment]
Sorry about that. Please update to [v1.5.3](https://github.com/vinceau/project-clippi/releases/tag/v1.5.3) which fixes this issue.
