### ISSUE TITLE
Error on attempted playback of .json

### ISSUE THREAD

**Issue by SoupOrJuice** [vinceau/project-clippi#123]
Creating the .json based on the combo profile works fine, but when it attempts to play it gets the errors shown in the attached images. ![1st Error](https://user-images.githubusercontent.com/20274390/117377277-e7175b00-aea0-11eb-9650-b6f1806cf065.png) 

then click OK and met with 

![2nd Error](https://user-images.githubusercontent.com/20274390/117377276-e67ec480-aea0-11eb-84c0-a0ce2e95caee.png)

I have the Melee ISO selected correctly and Slippi Dolphin v2.3.0 is connected to Clippi vs 1.5.3. Not sure what else to try.

**Comment by vinceau** [comment]
Your Desktop app and playback dolphin is out of date. Close all running instances of Dolphin and reinstall the desktop app from https://slippi.gg
