### ISSUE TITLE
Renaming replays results in some having random string appended

### ISSUE THREAD

**Issue by ncondron42** [vinceau/project-clippi#148]
Renaming files results in some replay filenames having _<5 random characters>.slp at the end of the filename.

This is the format string I'm using: "{{YY}}{{MM}}{{DD}}_{{HH}}{{mm}}_{{playerName}}_{{playerShortChar}}_v_{{opponentName}}_{{opponentShortChar}}_({{shortStage}}).slp"

Here are some of the results I get:
```
nick@nick-lenovo:/data/slp$ find . -name '*)_?????.slp' | head
./202201/220126_0230_Mr Plow_Falco_v_mang_Falco_(BF)_28ul1.slp
./202201/220112_2101_n3zmodgod_Yoshi_v_mang_Fox_(YS)_21cox.slp
./202201/220107_1807_mang_Fox_v_KoDoRiN_Marth_(BF)_51dpj.slp
./202201/220118_2152_mang_Fox_v_TheRealThing_Falco_(DL)_u9wji.slp
./202201/220130_1506_mang_Falco_v_Lucky_Fox_(DL)_pz91p.slp
./202201/220121_2248_mang_Fox_v_TheRealThing_Falco_(BF)_qr8ms.slp
./202201/220122_0214_mang_Fox_v_TheRealThing_Falco_(BF)_1v9t5.slp
./202201/220129_2056_Lucky_Fox_v_mang_Falco_(BF)_vk610.slp
./202201/220112_2335_mang_Fox_v_@boyo_boost_Marth_(FoD)_avvy1.slp
./202201/220120_2018_mang_Falco_v_aye or die_Fox_(BF)_m3uoq.slp
```

Most other files are renamed fine. I did rename ~20k replays at once so maybe that affected things.

**Comment by vinceau** [comment]
This happens when your template string is not unique enough. i.e. two or more games will map to the same string, and if so it will append a random string at the end.
If you don't want this to happen use a more unique template string like full timestamp.
