### ISSUE TITLE
Issue with recording clips

### ISSUE THREAD

**Issue by suckfingerduckkong** [vinceau/project-clippi#163]
Every time I go to start the automated recording with OBS, Slippi opens and before the clip can play I get an[ error.](https://imgur.com/a/8BRXfcP)
"Question
Delete the existing file 'C:/Users//Appdata/Roaming/Slippi Launcher/playback/User/Dump/Frames/framedump0.avi'?"

If I press yes, the clip will continue as normal until it is over and then the error repeats on the next clip. This no longer automates the process. If I press no, the error immediately returns and does every subsequent press. 

What do I do?

**Comment by vinceau** [comment]
You have frame dumping enabled in your Playback Dolphin. In Launcher Settings, go to Configure Playback Dolphin -> Movie -> Dump frames. And turn off that option.

**Comment by suckfingerduckkong** [comment]
> You have frame dumping enabled in your Playback Dolphin. In Launcher Settings, go to Configure Playback Dolphin -> Movie -> Dump frames. And turn off that option.

Thanks. Looked for something like this but didn't check Movie.
