### ISSUE TITLE
Clippi does not save name tag filter

### ISSUE THREAD

**Issue by barthosw** [vinceau/project-clippi#184]
Whenever I add a name tag filter and save the profile, my input is wiped after I switch screens and return to the combo filter. I also noticed that the name tag filter field is empty when I export the profile. I am not able to use name tag in my combo filter.

![image](https://github.com/vinceau/project-clippi/assets/54995273/925eec4d-e8da-48a3-a5bc-f9b43247a978)
![image](https://github.com/vinceau/project-clippi/assets/54995273/a8655af1-f5a7-472b-b3b1-b5196b525c10)

After closing settings and then returning to the combo filter.
![image](https://github.com/vinceau/project-clippi/assets/54995273/5e686949-5bd0-4d74-88ce-dd703e33f69f)

**Comment by vinceau** [comment]
You have to hit enter after typing in the Name Tag Filter. See if that solves your problem.

**Comment by barthosw** [comment]
Wow I am dumb! Sorry for wasting your time.
