### ISSUE TITLE
Using an invalid Renaming-Format

### ISSUE THREAD

**Issue by KingKonrad** [vinceau/project-clippi#70]
When using an invalid char in a Filename (I did it with ":") when entering a Renaming Format, there will be no on-screen error etc, but instead the progress-bar will stay at 0% with no possibility of stopping.

**Comment by vinceau** [comment]
Thanks for the report. I think we should add input-validation to the file rename format such that the "Start processing" button is disabled if the format is invalid, and a message is shown.
