### ISSUE TITLE
Ask to overwrite combos.json

### ISSUE THREAD

**Issue by Savestate2A03** [vinceau/project-clippi#81]
Hey, just spent about 30 minutes letting it go through a number of slippi files, and accidentally clicked "Process Highlights" again after it finished processing. Without a prompt, the combos file was overwritten and I had lost the data from the run. 

A prompt to overwrite would likely be helpful here, thank you!

**Comment by vinceau** [comment]
Thanks for the suggestion. Will consider it for the next release. :)

**Comment by vinceau** [comment]
Fixed in #80.

**Comment by Savestate2A03** [comment]
And with great speed ! Much appreciated
