### ISSUE TITLE
Ticking "Load into Dolphin" and then disabling "Find Highlights" still opens Dolphin

### ISSUE THREAD

**Issue by KingKonrad** [vinceau/project-clippi#87]
Ticking the box
![image](https://user-images.githubusercontent.com/56696636/86245088-42096300-bba9-11ea-943d-d4094a9ed3e9.png)
Then unselecting the category 
![image](https://user-images.githubusercontent.com/56696636/86245143-5a797d80-bba9-11ea-8543-a8f5272ac95a.png)
Still loads dolphin

**Comment by vinceau** [comment]
Thanks for the bug report! Will look into fixing it. :)

**Comment by vinceau** [comment]
Fixed in b2762c2.
