### ISSUE TITLE
Add Player "display name" or ConnectCode in Rename Files

### ISSUE THREAD

**Issue by Kounotori-ssbm** [vinceau/project-clippi#90]
I want "name" and "connect code" for "Rename files" option.
like `{playerName}`, `{opponentName}`, `{playerConnectCode}`, `{opponentConnectCode}`

I meant here.
![image](https://user-images.githubusercontent.com/19996147/86503572-6a33d480-bdea-11ea-9c15-befbfecb18ca.png)

e.g
format: `{{YYYY}}{{MM}}{{DD}}-{{HH}}{{mm}}_{{playerName}}({{playerShortChar}})-vs-{{opponentName}}({{opponentShortChar}})_{{shortStage}}.slp`
result: `20011122-0233_twitch.tv-oyost(Samus)-vs-Kounotori(Fox)_BF.slp`

though the chars which cannot be used as filename in playerName have to be replaced a certain char...

**Comment by vinceau** [comment]
This feature has been added to v1.4.0.

**Comment by Kounotori-ssbm** [comment]
thank you so much!!!
