### ISSUE TITLE
Playing a clip requires waiting for the scrollbar to catch up

### ISSUE THREAD

**Issue by phase** [vinceau/project-clippi#92]
I'm using Slippi 2.1.1 & Clippi 1.3.7.

When loading a clip into slippi, I have to wait for the scrollbar at the bottom to go to the time when the clip starts. It doesn't display the match and the time is sped up quite a bit, but for clips later in the match it can take a while.

**Comment by vinceau** [comment]
This is not an issue with Clippi. It's just the way that Slippi Dolphin handles playing back from a certain part of a file. It needs to "skip" to that part in the game by replaying all the inputs from the beginning of the game. Yes it can take a while, especially on slow computers, but there's nothing on Clippi's end that can be done.

**Comment by phase** [comment]
Ah that makes sense! Thanks for explaining that
