### ISSUE TITLE
The tutorial needs a entry to set melee ISO path

### ISSUE THREAD

**Issue by OscarDev** [vinceau/project-clippi#96]
I've read the tutorial 3 times and couldn't figure out what was wrong, until I guessed that iso hasn't been set. You should add this to your readme since I can't PR to medium

**Comment by vinceau** [comment]
Setting the Melee ISO is 100% optional. If the ISO is not set, you just have to double click Melee to start the playback. It's purely for convenience purposes and thus has been excluded for tutorial.

**Comment by vinceau** [comment]
It seems other people have also had an issue where the list of ISOs does not show up when opening Dolphin for them to select Melee. I'll add it to the tutorial to hopefully mitigate this in the future.

**Comment by OscarDev** [comment]
Thanks for developing such an awesome project :)
